const Catagories = [
    '🎭 Arts',
    '💅🏼 Beauty',
    '👢 Style',
    '🛎 Business',
    '🚗 Vehicles',
    '🖥 Computers',
    '📡 Internet',
    '⚡️ Electronics',
    '🍔 Food',
    '🧮 Education',
    '🎼 Music',
    '🎬 Movies',
    '📺 Shows',
    '🏔 Environment',
    '⛺️ Camping',
    '❤️ Relationships',
    '👨‍👩‍👧‍👦 Family',
    '🎲 Games',
    '🏈 Sports',
    '🏥 Health',
    '🧑🏻‍🌾 Gardening',
    '🎤 News',
    '🐾 Pets',
    '🗳️ Politics',
    '🤰 Pregnancy',
    '👩‍👧 Parenting',
    '🔬 Science',
    '➗ Math',
    '🏟 Culture',
    '🏙 Travel',
]

export default Catagories;